== Spring Cloud Stream Sample Applications

This repository contains a collection of applications written using Spring Cloud Stream. All the applications are self-contained.
They can be run against either Kafka or RabbitMQ middleware technologies.
You have the option of running the samples against local or Docker containerized versions of Kafka and Rabbit.

You can build the entire samples by going to the root of the repository and then execute: `./mvnw clean package`.

However, the recommended approach to build them is to pick the sample that you are interested in and go to that particular app and follow the instructions there in the README for that app. 

=== Provided Sample Applications

Below, you can find the list of all the provided sample applications.

==== Confluent Schema Registry Integration

This set of sample applications show how Spring Cloud Stream Kafka applications integrate with Confluent Schema Registry.
You can find more details at link:confluent-schema-registry-integration/README.adoc[README].

