== What is this app?

This is an example of a Spring Cloud Stream processor using Kafka Streams support.

This example is a Spring Cloud Stream adaptation of this Kafka Streams sample: https://github.com/confluentinc/kafka-streams-examples/tree/4.0.0-post/src/main/java/io/confluent/examples/streams/interactivequeries/kafkamusic

This sample demonstrates the concept of interactive queries in kafka streams.
There is a REST service provided as part of the application that can be used to query the store interactively.

==== Starting Kafka in a docker container

* Skip these steps if you already have a non-Docker Kafka environment.

1. Go to the docker directory in this repo and invoke the command `docker-compose up -d`.
2. Ensure that in the docker directory and then invoke the script `start-kafka-shell.sh`

=== Running the app:

1. Start the confluent schema registry: The following command is based on the confluent platform.

`./bin/schema-registry-start ./etc/schema-registry/schema-registry.properties`

2. Go to the root of the repository and do: `./mvnw clean package`

`java -jar target/kafka-streams-interactive-query-0.0.1-SNAPSHOT.jar`

3. Run the stand-alone `Producers` application to generate data and start the processing.
Keep it running for a while.

4. Go to the URL: http://localhost:8080/charts/top-five?genre=Punk
keep refreshing the URL and you will see the song play count information changes.

* By default we use the docker container IP (mac osx specific) in the `application.yml` for Kafka broker and zookeeper.
Change it in `application.yml` (which requires a rebuild) or pass them as runtime arguments as below.

`spring.cloud.stream.kstream.binder.brokers=<Broker IP Address>` +
`spring.cloud.stream.kstream.binder.zkNodes=<Zookeeper IP Address>`

