== What is this app?

This is an example using Spring Cloud Stream to model a subset of a purchasing system. This e2e project showcases the following
features:

* Avro messaging
* Confluent Schema Registry
* Event-carried state transfer pattern
* KStream processing with a join operation

=== Running the app:

Start the Confluent Platform:

```
git clone https://github.com/confluentinc/cp-docker-images
cd cp-docker-images
git checkout 5.2.1-post
cd examples/cp-all-in-one/
docker-compose up -d --build
```

Go to the root of the sample project and do:

`./mvnw clean package`

`java -jar customer-service/target/customer-service-0.0.1-SNAPSHOT.jar`

`java -jar order-service/target/order-service-0.0.1-SNAPSHOT.jar`

`java -jar shipping-service/target/shipping-service-0.0.1-SNAPSHOT.jar`

Create a customer:

`curl -X POST http://localhost:8084/customers -d '{"id":1,"name":"John Doe","address":"Elm Street"}' -H "content-type: application/json"`

Create an order for that customer:

`curl -X POST http://localhost:8085/orders -H "content-type: application/json" -d '{"id":1,"productId":100,"customerId":1}'`

Check the order topic content to verify that there are two records corresponding to the OrderCreatedEvent from customer-service
and the OrderShippedEvent from shipping-service.

Then go to the URL: http://localhost:8080/events

