== What is this app?

This is an example of a Spring Cloud Stream processor using Kafka Streams branching support.

The example is based on the word count application from the https://github.com/confluentinc/examples/blob/3.2.x/kafka-streams/src/main/java/io/confluent/examples/streams/WordCountLambdaExample.java[reference documentation].
It uses a single input and 3 output destinations.
In essence, the application receives text messages from an input topic, filter them by language (Englihs, French, Spanish and ignoring the rest), and computes word occurrence counts in a configurable time window and report that in the output topics.
This sample uses lambda expressions and thus requires Java 8+.

By default native decoding and encoding are disabled and this means that any deserializaion on inbound and serialization on outbound is performed by the Binder using the configured content types.

==== Starting Kafka in a docker container

* Skip steps 1-3 if you already have a non-Docker Kafka environment.

1. Go to the docker directory in this repo and invoke the command `docker-compose up -d`.
2. Ensure that in the docker directory and then invoke the script `start-kafka-shell.sh`
3. cd $KAFKA_HOME
4. Start the console producer: +
Assuming that you are running kafka on a docker container on mac osx. Change the zookeeper IP address accordingly otherwise. +
`bin/kafka-console-producer.sh --broker-list 192.168.99.100:9092 --topic words`
5. Start the console consumer: +
Assuming that you are running kafka on a docker container on mac osx. Change the zookeeper IP address accordingly otherwise. +
a. `bin/kafka-console-consumer.sh --bootstrap-server 192.168.99.100:9092 --topic english-counts`
b. On another console: `bin/kafka-console-consumer.sh --bootstrap-server 192.168.99.100:9092 --topic french-counts`
c. On another console: `bin/kafka-console-consumer.sh --bootstrap-server 192.168.99.100:9092 --topic spanish-counts`

=== Running the app:

Go to the root of the repository and do: `./mvnw clean package`

`java -jar target/kafka-streams-branching-0.0.1-SNAPSHOT.jar --spring.cloud.stream.kafka.streams.timeWindow.length=60000`

* By default we use the docker container IP (mac osx specific) in the `application.yml` for Kafka broker and zookeeper.
Change it in `application.yml` (which requires a rebuild) or pass them as runtime arguments as below.

`spring.cloud.stream.kafka.streams.binder.brokers=<Broker IP Address>` +
`spring.cloud.stream.kafka.streams.binder.zkNodes=<Zookeeper IP Address>`

Enter text ("English", "French", "Spanish" - case doesn't matter) in the console producer and watch the output in the respective console consumer - The word "english" goes to topic english-counts, "french" goes to topic french-counts and "spanish" goes to spanish-counts.

In order to switch to a hopping window, you can use the `spring.cloud.stream.kafka.streams.timeWindow.advanceBy` (value in milliseconds).
This will create an overlapped hopping windows depending on the value you provide.

Here is an example with 2 overlapping windows (window length of 10 seconds and a hop (advance) by 5 seconds:

`java -jar target/kafka-streams-branching-0.0.1-SNAPSHOT.jar --spring.cloud.stream.kafka.streams.timeWindow.length=10000 --spring.cloud.stream.kafka.streams.timeWindow.advanceBy=5000`
